### ISSUE TITLE
Folia support

### ISSUE THREAD

**Issue by haha44444** [OneLiteFeatherNET/AntiRedstoneClock-Remastered#32]
As the title.

**Comment by TheMeinerLP** [comment]
Folia Support is more complicated because not all events are working to 100%

**Comment by TheMeinerLP** [comment]
Is this still up to date?
Has it ever been tested with Folia?

**Comment by TheMeinerLP** [comment]
No response, the issues will be close!

**Comment by TheMeinerLP** [comment]
Hi @haha44444 test the following Pre-Release: https://github.com/OneLiteFeatherNET/AntiRedstoneClock-Remastered/releases/tag/v2.3.0-beta.1

Please give us feedback
