### ISSUE TITLE
The plugin does not work

### ISSUE THREAD

**Issue by F3F5** [OneLiteFeatherNET/AntiRedstoneClock-Remastered#50]
The original arc works

https://github.com/OneLiteFeatherNET/AntiRedstoneClock-Remastered/assets/108226177/9c22c32d-b941-4d2b-8736-3f8a50129238

**Comment by TheMeinerLP** [comment]
Please provide complete steps of reproduce. Also version of the plugins, server

**Comment by F3F5** [comment]
> Please provide complete steps of reproduce. Also version of the plugins, server

https://github.com/OneLiteFeatherNET/AntiRedstoneClock-Remastered/actions/runs/7811134502 - version.
and you can see server ver in video

**Comment by TheMeinerLP** [comment]
Can you please write it down? It's more simple for us

**Comment by OneLiteFeather** [comment]
We also need your config if you made any changes there. You have to set it up for it to work

**Comment by F3F5** [comment]
default config without any changes

**Comment by OneLiteFeather** [comment]
> default config without any changes

well then go to your config and include your world so that the plugin logic is working in your world

**Comment by F3F5** [comment]
it's simple "world" name

**Comment by OneLiteFeather** [comment]
You need to remove "world" properly so that the logic includes this world, as written in the Readme. Here is the default config:
https://github.com/OneLiteFeatherNET/AntiRedstoneClock-Remastered/blob/4a0e3d311404c64b60c9ed51025d909d05664319/src/main/resources/config.yml#L9
