### ISSUE TITLE
Plugin doesn't seem to work

### ISSUE THREAD

**Issue by trushniuser** [OneLiteFeatherNET/AntiRedstoneClock-Remastered#74]
Using the latest version of Paper 1.20.6 with latest version of Plotsquared 7.3.8-Premium and latest version of AntiRedstoneClock-Remastered loaded from modrinth plugin doesn't seem to work at all. Even with redstone-clock flag disabled on plot, they're not even counted in /arcm display. Only one error in console: https://pastebin.com/9N1z2nsG 
![image](https://github.com/OneLiteFeatherNET/AntiRedstoneClock-Remastered/assets/101549506/ed5b795f-94c8-41ab-8761-1a29988be956)
![image](https://github.com/OneLiteFeatherNET/AntiRedstoneClock-Remastered/assets/101549506/000ec6af-c4af-4fa8-9779-5b944e0857bd)

**Comment by TheMeinerLP** [comment]
The error in the console is not reproducible on a new server set up in 1.20.6 Paper
