### ISSUE TITLE
Sculk Snesors don't get detected

### ISSUE THREAD

**Issue by RyanoDino** [OneLiteFeatherNET/AntiRedstoneClock-Remastered#85]
### Server Logs

not give any errors

### Expected behavior

During cycles made with the sculk sensor, the sculk sensor breaks and drop

### Actual behavior

During cycles made with the sculk sensor, the sculk sensor breaks but not drop

### Steps to reproduce

https://youtu.be/N2zdgaNpuMY

### Plugin and Datapack List

https://prnt.sc/SPR4nGKzrDQ6

not have datapack

### Paper version

https://prnt.sc/Z6bwfS6Oty2t

### Plugin version

https://prnt.sc/HQs7Phu9rm2U

### Other

I guess sculk sensor break only with silktouch  therefore not drop(forecast)

**Comment by TheMeinerLP** [comment]
Update to 1.2.1
